---
title: "Interpretación de Sondeo Eléctrico Vertical"
output: html_document
params:
  current.ves: NA
---

```{r load_lib,echo=FALSE}
# The `params` object is available in the document.
library(rves)
library(knitr)
```

La información de espaciamiento y resistividades aparentes se presenta en la siguiente tabla:
```{r table_data,echo=FALSE}
spacing <- params$current.ves$ab2
apprho <- params$current.ves$appres
ves.df <- data.frame("AB/2" = spacing, "ApparentResitivity" = apprho)
kable(ves.df, format = "html", digits = 3, align = c('c','c'), caption = "VES DATA")
```

El gráfico del sondeo eléctrico vertical y su interpretación se presenta en la siguiente figura:
```{r plot.ves,echo=FALSE}
plot(params$current.ves, type = "ves")
``` 

```{r def_values,echo=FALSE}
rho.true <- params$current.ves$rhopar
thickness <- params$current.ves$thickpar
interpretation.ves <- cbind(rho.true, thickness)
interpretation.ves.df <- as.data.frame(interpretation.ves)
names(interpretation.ves.df) <- c("TrueResistivity", "Thickness")
nlayers <- length(rho.true)
layers.id <- vector("character", length = nlayers)
for(i in 1:nlayers){
  layers.id[i] <- paste0("Layer", as.character(i))
}
row.names(interpretation.ves.df) <- layers.id
kable(interpretation.ves.df, format = "html", digits = 3, align = c('l','r'), 
      caption = "MODELO DE CAPAS")
```
